# Generated by Django 5.1.15 on 2026-03-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_link',
        ),
        migrations.AddField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_page',
            field=models.ForeignKey(blank=True, help_text='Select the Newsletter Signup form page. The footer will submit emails directly to this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
